In [114]:
'''This module is for digitizing all features unless they are already digit.
Solution: 
            If any element of a column is not real, create a sorted set by all elements of this column, then give an unique id for each original data.
            Else nothing to do.
@Marc
 '''
import numpy as np
import pandas as pd

#encode for single column
def encodeColumn(col):
    encodedList = sorted(list(set(col)))
    for i in range(len(col)):
        element = col[i]
        col[i] = encodedList.index(element)
    return col

#encode for a matrix
def encodeMatrix(matrix):
    shape = matrix.shape
    for col in range(shape[1]):
        if not np.isreal(matrix[:, col].any()):
            matrix[:, col] = encodeColumn(matrix[:, col])
    return matrix

In [115]:
data_trains = np.array(pd.read_table('adult.data',sep = ',',header=None,engine='python'))
x_train = data_trains[:,:-1]
y_train = data_trains[:,-1]
x_train_digit = encodeMatrix(x_train)
y_train_digit = encodeColumn(y_train)
print(x_train_digit[:20])
print(y_train_digit[:20])

[[39 7 77516 9 13 4 1 1 4 1 2174 0 40 39]
 [50 6 83311 9 13 2 4 0 4 1 0 0 13 39]
 [38 4 215646 11 9 0 6 1 4 1 0 0 40 39]
 [53 4 234721 1 7 2 6 0 2 1 0 0 40 39]
 [28 4 338409 9 13 2 10 5 2 0 0 0 40 5]
 [37 4 284582 12 14 2 4 5 4 0 0 0 40 39]
 [49 4 160187 6 5 3 8 1 2 0 0 0 16 23]
 [52 6 209642 11 9 2 4 0 4 1 0 0 45 39]
 [31 4 45781 12 14 4 10 1 4 0 14084 0 50 39]
 [42 4 159449 9 13 2 4 0 4 1 5178 0 40 39]
 [37 4 280464 15 10 2 4 0 2 1 0 0 80 39]
 [30 7 141297 9 13 2 10 0 1 1 0 0 40 19]
 [23 4 122272 9 13 4 1 3 4 0 0 0 30 39]
 [32 4 205019 7 12 4 12 1 2 1 0 0 50 39]
 [40 4 121772 8 11 2 3 0 1 1 0 0 40 0]
 [34 4 245487 5 4 2 14 0 0 1 0 0 45 26]
 [25 6 176756 11 9 4 5 3 4 1 0 0 35 39]
 [32 4 186824 11 9 4 7 4 4 1 0 0 40 39]
 [38 4 28887 1 7 2 12 0 4 1 0 0 50 39]
 [43 6 292175 12 14 0 4 4 4 0 0 0 45 39]]
[0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1]


In [116]:
data_test = np.array(pd.read_table('adult.test',sep = ',',header=None,skiprows=[0],engine='python'))
x_test = data_test[:,:-1]
y_test = data_test[:,-1]
x_test_digit = encodeMatrix(x_test)
y_test_digit = encodeColumn(y_test)
print(x_train_digit[:20])
print(y_train_digit[:20])

[[39 7 77516 9 13 4 1 1 4 1 2174 0 40 39]
 [50 6 83311 9 13 2 4 0 4 1 0 0 13 39]
 [38 4 215646 11 9 0 6 1 4 1 0 0 40 39]
 [53 4 234721 1 7 2 6 0 2 1 0 0 40 39]
 [28 4 338409 9 13 2 10 5 2 0 0 0 40 5]
 [37 4 284582 12 14 2 4 5 4 0 0 0 40 39]
 [49 4 160187 6 5 3 8 1 2 0 0 0 16 23]
 [52 6 209642 11 9 2 4 0 4 1 0 0 45 39]
 [31 4 45781 12 14 4 10 1 4 0 14084 0 50 39]
 [42 4 159449 9 13 2 4 0 4 1 5178 0 40 39]
 [37 4 280464 15 10 2 4 0 2 1 0 0 80 39]
 [30 7 141297 9 13 2 10 0 1 1 0 0 40 19]
 [23 4 122272 9 13 4 1 3 4 0 0 0 30 39]
 [32 4 205019 7 12 4 12 1 2 1 0 0 50 39]
 [40 4 121772 8 11 2 3 0 1 1 0 0 40 0]
 [34 4 245487 5 4 2 14 0 0 1 0 0 45 26]
 [25 6 176756 11 9 4 5 3 4 1 0 0 35 39]
 [32 4 186824 11 9 4 7 4 4 1 0 0 40 39]
 [38 4 28887 1 7 2 12 0 4 1 0 0 50 39]
 [43 6 292175 12 14 0 4 4 4 0 0 0 45 39]]
[0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 1]
